---
- name: 2.1.1 Ensure that the --anonymous-auth argument is set to false (Scored)
  debug: msg="***Manually verify anonymous enabled false in /var/lib/kubelet/config.yaml "
  tags:
    - section2.1.1
    - node
    - scored
    - level1

- name: 2.1.2 Ensure that the --authorization-mode argument is not set to AlwaysAllow (Scored)
  debug: msg="***Manually verify authorization mode is not AlwaysAllow in /var/lib/kubelet/config.yaml "
  tags:
    - section2.1.2
    - node
    - scored
    - level1

- name: 2.1.3 Ensurethat the --client-ca-file argument is set as appropriate (Scored)
  debug: msg="***Manually verify set authentication x509 clientCAFile to the location of the client CA file in /var/lib/kubelet/config.yaml "
  tags:
    - section2.1.3
    - node
    - scored
    - level1

- name: 2.1.4 Ensurethat the --read-only-port argument is set to 0 (Scored)
  lineinfile:
    path: /var/lib/kubelet/config.yaml
    line: "readOnlyPort: 0"
    insertafter: "resolvConf: /etc/resolv.conf"
  tags:
    - section2.1.4
    - node
    - scored
    - level1

- name: 2.1.5 Ensure that the --streaming-connection-idle-timeout argument is not set to 0 (Scored)
  lineinfile:
    path: /var/lib/kubelet/config.yaml
    line: "streamingConnectionIdleTimeout: 0"
    state: absent
  tags:
      - section2.1.5
      - node
      - scored
      - level1
      
- name: 2.1.6 Ensure that the --protect-kernel-defaults argument is set to true (Scored)
  lineinfile:
    path: /var/lib/kubelet/config.yaml
    line: "protectKernelDefaults: true"
    state: present
  tags:
    - section2.1.6
    - node
    - scored
    - level1
    
- name: post 2.1.6
  copy: src=90-kubelet.conf dest=/etc/sysctl.d/90-kubelet.conf owner=root group=root mode=0640
  tags:
    - section2.1.6
    - node
    - scored
    - level1
#vm.overcommit_memory=1
#kernel.panic=10
#kernel.panic_on_oops=1

- name: 2.1.7 Ensure that the --make-iptables-util-chains argument is set to true (Scored)
  lineinfile:
    path: /var/lib/kubelet/config.yaml
    line: "makeIPTablesUtilChains: true"
    state: present
  tags:
    - section2.1.7
    - node
    - scored
    - level1
    
- name: 2.1.8 Ensure that the --hostname-override argument is not set (Scored)
  lineinfile:
    path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    regexp: "--hostname-override"
    state: absent
  tags:
    - section2.1.9
    - node
    - scored
    - level1
#not available in kubelet config file
    
- name: 2.1.9 Ensure that the --event-qps argument is set to 0 (Scored)
  lineinfile:
    path: /var/lib/kubelet/config.yaml
    regexp: "^eventRecordQPS:*"
    line: "eventRecordQPS: 0"
  tags:
    - section2.1.9
    - node
    - scored
    - level1
    
- name: 2.1.10 Ensure that the --tls-cert-file and --tls-private-key-file arguments are set as appropriate (Scored)
  debug: msg="*** Manually verify that the --tls-cert-file and --tls-private-key-file arguments exist and they are set as appropriate."
  tags:
    - section2.1.10
    - node
    - scored
    - level1
    
- name: 2.1.11 Ensure that the --cadvisor-port argument is set to 0 (Scored)
  debug: msg="*** Not available in K8S version 1.12 onwards"
  tags:
    - section2.1.11
    - node
    - scored
    - level1
    
- name: 2.1.12 Ensure that the --rotate-certificates argument is not set to false (Scored)
  lineinfile:
    path: /var/lib/kubelet/config.yaml
    line: "rotateCertificates: true"
    state: present
  tags:
    - section2.1.12
    - node
    - scored
    - level1
    
- name: 2.1.13 Ensure that the RotateKubeletServerCertificate argument is set to true (Scored)
  debug: msg="*** This features is enabled by default according to https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/#using-a-feature"
  tags:
    - section2.1.13
    - node
    - scored
    - level1

- name: 2.1.14 Ensure that the Kubelet only makes use of Strong Cyptograhic Ciphers (Not Scored)
  lineinfile:
    path: /var/lib/kubelet/config.yaml
    line: "tls-cipher-suites: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256"
    state: present
  tags:
    - section2.1.4
    - node
    - level1
    - notscored
    
- name: 2.2.1 Ensure that the kubelet.conf file permissions are set to 644 or more restrictive (Scored)
  file: path=/etc/kubernetes/kubelet.conf mode=0644
  tags:
    - section2.2.1
    - node
    - level1
    - scored
    
- name: 2.2.2 Ensure that the kubelet.conf file ownership is set to root:root (Scored)
  file: path=/etc/kubernetes/kubelet.conf owner=root group=root
  tags:
    - section2.2.2
    - node
    - level1
    - scored
    
- name: 2.2.3 Ensure that the kublet service file permissions are set to 644 or more restrictive (Scored)
  debug: msg="*** file not exists"
  tags:
    - section2.2.3
    - node
    - level1
    - scored

- name: 2.2.4 Ensure that the kubelet service file ownership is set to root:root (Scored)
  debug: msg="*** file not exists"
  tags:
    - section2.2.4
    - node
    - level1
    - scored
    
- name: 2.2.5 Ensure that the proxy kubeconfig file permissions are set to 644 or more restrictive (Scored)
  debug: msg="*** file not exists"
  tags:
    - section2.2.5
    - node
    - level1
    - scored
    
- name: 2.2.6 Ensure that the proxy kubeconfig file ownership is set to root:root (Scored)
  debug: msg="*** file not exists"
  tags:
    - section2.2.6
    - node
    - level1
    - scored

- name: 2.2.7 Ensure that the certificate authorities file permissions are set to 644 or more restrictive (Scored)
  file: path=/etc/kubernetes/pki/ca.crt mode=0644
  tags:
    - section2.2.7
    - node
    - level1
    - scored
    
- name: 2.2.8 Ensure that the client certificate authorities file ownership is set to root:root (Scored)
  file: path=/etc/kubernetes/pki/ca.crt owner=root group=root
  tags:
    - section2.2.8
    - node
    - level1
    - scored
    
- name: 2.2.9 Ensure that the kubelet configuration file ownership is set to root:root (Scored)
  file: path=/var/lib/kubelet/config.yaml owner=root group=root
  tags:
    - section2.2.9
    - node
    - level1
    - scored
    
- name: 2.2.10 Ensure that the kubelet configuration file has permissions set to 644 or more restrictive (Scored)
  file: path=/var/lib/kubelet/config.yaml mode=0644
  tags:
    - section2.2.10
    - node
    - level1
    - scored













    